### ISSUE TITLE
Not working on MiSTer

### ISSUE THREAD

**Issue by mario-64** [qwertymodo/LADX-MSU1#2] opened 2022-08-09 14:15 UTC
Unfortunately the patch isn't working on my MiSTer, not the MSU1 part anyway. It just gets loaded as a regular SGB rom.
All files are in a folder and the gbc and msu files are both named "Link's Awakening DX MSU1". What am I missing?

**Comment by qwertymodo** [comment] 2022-08-09 15:45
Does the MSU-1 splash screen show up on boot? Do you hear normal music when you play? It sounds like you didn't patch your GB ROM file correctly.

**Comment by mario-64** [comment] 2022-08-09 16:13
Thanks for the help. I don't get the MSU-1 splash screen when the game boots. I'll try patching the rom again and report back.

**Comment by mario-64** [comment] 2022-08-09 16:34
I re-patched the ROM and it loads now. However, on MiSTer something is off with input. It's like Turbo is enabled for all buttons and even the dpad/joystick.  For example when you get to the name entry screen and press a button to select a letter it gets added 3 times.  And Navigating the letter select menu with either dpad or joystick is nearly impossible because of how fast the cursor jumps with one press. 
I tested both SGB1 and SGB1 bioses as well as all SGB1, SGB2 and SNES speed options in the core. Nothing fixes it. The unpatched ROM does not have this issue.

**Comment by qwertymodo** [comment] 2022-08-09 21:20
Since we figured out the original issue was due to a bad patch, I'm going to close this as a duplicate of https://github.com/qwertymodo/LADX-MSU1/issues/1 and track the "turbo button" behavior issue there.

**Closed as completed by qwertymodo** 2022-08-09 21:20 UTC
