### ISSUE TITLE
On FXPak Pro holding a button acts as multiple button presses.

### ISSUE THREAD

**Issue by Eloeri** [qwertymodo/LADX-MSU1#1] opened 2022-08-09 14:02 UTC
When trying to input name for a new game, just barely pressing the D-Pad or face buttons would register multiple button presses simultaneously, sort of like turbo mode. Tested other gameboy games, and they act normally. 

The music sounds great from the title screen to Marin and Tarin's house, no issues there.

Using FXPak Pro firmware 1.11.0 beta 1 with Redacted173's SGB firmware SGB07, Super Gameboy 2 files are reported as being correct in the FXPak pro's system menu.

**Comment by qwertymodo** [comment] 2022-08-09 18:00
Which version of the game did you apply the patch to?  I've gotten multiple reports of this now, but am having trouble replicating the issue.

**Comment by Eloeri** [comment] 2022-08-09 18:54
`Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev B) (SGB Enhanced) (GB Compatible)` 

<img width="675" alt="image" src="https://user-images.githubusercontent.com/42394653/183738949-e02511eb-04ed-4150-935f-66de4f2f62ae.png">

**Comment by Eloeri** [comment] 2022-08-09 20:19
Tested with versions 1.1 and 1.0, using the correct .bps patch files, all run the same. Audio sounds good, great even, but the controls are "turbo".

**Comment by qwertymodo** [comment] 2022-08-09 21:24
> Tested with versions 1.1 and 1.0, using the correct .bps patch files, all run the same. Audio sounds good, great even, but the controls are "turbo".

Just to be perfectly clear, did you test the PATCH version 1.0, or did you test ROM revision 1.0?  Because I played patch version 1.0 start to finish on the SD2SNES and never experienced this issue, which would lead me to believe it's an issue with your FXPAK configuration if you're experiencing the issue on patch 1.0.  If instead you mean you tested ROM revision 1.0 and 1.1, both with patch version 1.1, then that would lead to an entirely different conclusion.

**Comment by mario-64** [comment] 2022-08-09 21:47
I'm experiencing this same issue with MiSTer. I used the 1.2 patch against the Rev 2/Rev B game ROM.

**Comment by RaspberryAlpine** [comment] 2022-08-09 22:05
I am having this issue (turbo inputs) with ladx-msu1_v1.1 as well on MiSTer SGB core. 

Patch used: ladx_u1.2-msu1.bps

The rom that was patched: Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev B) (SGB Enhanced).gbc

I didn’t have the issue with ladx-msu1_v1.0

I also didn’t have the issue when loading the patched v1.1 rom in the MiSTer Gameboy core. Of course there was no music but that was expected.

**Comment by qwertymodo** [comment] 2022-08-09 22:06
> I am having this issue (turbo inputs) with ladx-msu1_v1.1 as well on MiSTer SGB core.
> I didn’t have the issue with ladx-msu1_v1.0

Ok, this is good information, because it means it's probably fixable on my end.  I'm going to be pretty busy for the rest of the week, so I don't know when I'll be able to get around to it, but it's definitely on my radar to fix.

**Comment by Eloeri** [comment] 2022-08-09 22:42
> > Tested with versions 1.1 and 1.0, using the correct .bps patch files, all run the same. Audio sounds good, great even, but the controls are "turbo".
> 
> Just to be perfectly clear, did you test the PATCH version 1.0, or did you test ROM revision 1.0? Because I played patch version 1.0 start to finish on the SD2SNES and never experienced this issue, which would lead me to believe it's an issue with your FXPAK configuration if you're experiencing the issue on patch 1.0. If instead you mean you tested ROM revision 1.0 and 1.1, both with patch version 1.1, then that would lead to an entirely different conclusion.

I used the patch 1.0 with rom 1.0, and patch 1.1 with rom 1.1. Is that not the correct way to apply the patches?

1.0:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/42394653/183774338-b9e26c4d-d39d-4a3c-8dc2-2567f3e35ac5.png">

1.1:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/42394653/183774391-a3efdb0a-8019-4642-ad9c-edabe9750ad8.png">

With their corresponding patches: 
<img width="105" alt="image" src="https://user-images.githubusercontent.com/42394653/183774456-4fde15d4-48a1-4b8f-92f4-f26e671f12d0.png">

**Comment by qwertymodo** [comment] 2022-08-09 22:45
> I used the patch 1.0 with rom 1.0, and patch 1.1 with rom 1.1. Is that not the correct way to apply the patches?

When I say patch 1.0, I mean the version of the patch released two years ago, available [here](https://github.com/qwertymodo/LADX-MSU1/releases/tag/v1.0).  Patch version 1.1 was released yesterday, available [here](https://github.com/qwertymodo/LADX-MSU1/releases/tag/v1.1).  Within each of those releases are multiple patch files, meant for use with each different release of the game.  From your screenshot, it appears you are using patch version 1.1 in both instances, for ROM version U1.0 and U1.1.  I know it's confusing, not much I can do about that, sorry...

**Comment by qwertymodo** [comment] 2022-08-09 22:47
If both of those patch files came out of the same zip file, then they are both the same version of the patch.

**Comment by Eloeri** [comment] 2022-08-09 22:58
Ah, yeah, sorry! Yes, the patch files were downloaded today, so I am using the LADX-MSU1 version 1.1, making sure to use the correct .bps files with their respective rom versions.

**Comment by qwertymodo** [comment] 2022-08-09 23:02
Great, now that we're definitely on the same page, could you possibly download the older patch set that I linked above and test them out to see whether or not the issue existed in my older release?  I only need it tested on a single ROM revision at this point, doesn't matter which one.  Based on @RaspberryAlpine's report above, it sounds like the issue didn't exist in the older release, and a second confirmation of that would be very helpful in tracking down the root cause.

**Comment by Eloeri** [comment] 2022-08-09 23:03
Definitely, will do.

**Comment by Eloeri** [comment] 2022-08-09 23:10
The problem is not present in LADX-MSU1 version 1.0. All button inputs are correct.

**Comment by qwertymodo** [comment] 2022-08-09 23:18
Ok, that gives me a pretty good idea of where to look.  Give this a try and let me know if it's fixed.

[ladx-msu1_20220809.zip](https://github.com/qwertymodo/LADX-MSU1/files/9295115/ladx-msu1_20220809.zip)

**Comment by RaspberryAlpine** [comment] 2022-08-09 23:27
The new patch (ladx-msu1_20220809.zip) did not fix the turbo button issue on MiSTer SGB.

**Comment by qwertymodo** [comment] 2022-08-09 23:28
Darn, of course it couldn't be that easy...

**Comment by Eloeri** [comment] 2022-08-09 23:35
And it did not fix the issue on FXPak Pro.

**Comment by qwertymodo** [comment] 2022-08-14 16:41
I'm still kind of stabbing in the dark on this one, but here's a new test build to try out.

[ladx-msu1_20220814.zip](https://github.com/qwertymodo/LADX-MSU1/files/9333734/ladx-msu1_20220814.zip)

**Comment by RaspberryAlpine** [comment] 2022-08-14 17:14
Just tested ladx-msu1_20220814 on MiSTer SGB and the turbo inputs issue persists.

**Comment by qwertymodo** [comment] 2022-08-14 17:32
Ok, that's actually good news. If that had fixed it, that would have been about the worst case scenario for a proper fix.  Just as a sanity check, can you try this one?  If this one fixes it, that gives me a much clearer idea of where to be looking.

[ladx-msu1_20220814-2.zip](https://github.com/qwertymodo/LADX-MSU1/files/9333817/ladx-msu1_20220814-2.zip)

**Comment by RaspberryAlpine** [comment] 2022-08-14 17:38
ladx-msu1_20220814-2 seems to have fixed it, no turbo inputs.

**Comment by qwertymodo** [comment] 2022-08-14 17:39
Perfect, that points me in the right direction.

**Comment by qwertymodo** [comment] 2022-08-16 00:37
Ok, should be fixed now.  Download https://github.com/qwertymodo/LADX-MSU1/releases/tag/v1.1a

**Closed as completed by qwertymodo** 2022-08-16 00:37 UTC

**Comment by RaspberryAlpine** [comment] 2022-08-16 01:35
This update, v1.1a, fixed the turbo inputs issue on MiSTer SGB and on SD2SNES Pro Super Nt. Thanks for the fix.

**Comment by mario-64** [comment] 2022-08-17 01:05
Thanks for the fix
